/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuralToolkitRouteImport } from './routes/structural-toolkit'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectManagerRouteImport } from './routes/project-manager'
import { Route as FileManagerRouteImport } from './routes/file-manager'
import { Route as FeeManagerRouteImport } from './routes/fee-manager'
import { Route as CalculationDocsRouteImport } from './routes/calculation-docs'
import { Route as AskEulerRouteImport } from './routes/ask-euler'
import { Route as IndexRouteImport } from './routes/index'

const StructuralToolkitRoute = StructuralToolkitRouteImport.update({
  id: '/structural-toolkit',
  path: '/structural-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectManagerRoute = ProjectManagerRouteImport.update({
  id: '/project-manager',
  path: '/project-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FileManagerRoute = FileManagerRouteImport.update({
  id: '/file-manager',
  path: '/file-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeManagerRoute = FeeManagerRouteImport.update({
  id: '/fee-manager',
  path: '/fee-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculationDocsRoute = CalculationDocsRouteImport.update({
  id: '/calculation-docs',
  path: '/calculation-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AskEulerRoute = AskEulerRouteImport.update({
  id: '/ask-euler',
  path: '/ask-euler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-euler': typeof AskEulerRoute
  '/calculation-docs': typeof CalculationDocsRoute
  '/fee-manager': typeof FeeManagerRoute
  '/file-manager': typeof FileManagerRoute
  '/project-manager': typeof ProjectManagerRoute
  '/settings': typeof SettingsRoute
  '/structural-toolkit': typeof StructuralToolkitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-euler': typeof AskEulerRoute
  '/calculation-docs': typeof CalculationDocsRoute
  '/fee-manager': typeof FeeManagerRoute
  '/file-manager': typeof FileManagerRoute
  '/project-manager': typeof ProjectManagerRoute
  '/settings': typeof SettingsRoute
  '/structural-toolkit': typeof StructuralToolkitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-euler': typeof AskEulerRoute
  '/calculation-docs': typeof CalculationDocsRoute
  '/fee-manager': typeof FeeManagerRoute
  '/file-manager': typeof FileManagerRoute
  '/project-manager': typeof ProjectManagerRoute
  '/settings': typeof SettingsRoute
  '/structural-toolkit': typeof StructuralToolkitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-euler'
    | '/calculation-docs'
    | '/fee-manager'
    | '/file-manager'
    | '/project-manager'
    | '/settings'
    | '/structural-toolkit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-euler'
    | '/calculation-docs'
    | '/fee-manager'
    | '/file-manager'
    | '/project-manager'
    | '/settings'
    | '/structural-toolkit'
  id:
    | '__root__'
    | '/'
    | '/ask-euler'
    | '/calculation-docs'
    | '/fee-manager'
    | '/file-manager'
    | '/project-manager'
    | '/settings'
    | '/structural-toolkit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskEulerRoute: typeof AskEulerRoute
  CalculationDocsRoute: typeof CalculationDocsRoute
  FeeManagerRoute: typeof FeeManagerRoute
  FileManagerRoute: typeof FileManagerRoute
  ProjectManagerRoute: typeof ProjectManagerRoute
  SettingsRoute: typeof SettingsRoute
  StructuralToolkitRoute: typeof StructuralToolkitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structural-toolkit': {
      id: '/structural-toolkit'
      path: '/structural-toolkit'
      fullPath: '/structural-toolkit'
      preLoaderRoute: typeof StructuralToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-manager': {
      id: '/project-manager'
      path: '/project-manager'
      fullPath: '/project-manager'
      preLoaderRoute: typeof ProjectManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-manager': {
      id: '/file-manager'
      path: '/file-manager'
      fullPath: '/file-manager'
      preLoaderRoute: typeof FileManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-manager': {
      id: '/fee-manager'
      path: '/fee-manager'
      fullPath: '/fee-manager'
      preLoaderRoute: typeof FeeManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculation-docs': {
      id: '/calculation-docs'
      path: '/calculation-docs'
      fullPath: '/calculation-docs'
      preLoaderRoute: typeof CalculationDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-euler': {
      id: '/ask-euler'
      path: '/ask-euler'
      fullPath: '/ask-euler'
      preLoaderRoute: typeof AskEulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskEulerRoute: AskEulerRoute,
  CalculationDocsRoute: CalculationDocsRoute,
  FeeManagerRoute: FeeManagerRoute,
  FileManagerRoute: FileManagerRoute,
  ProjectManagerRoute: ProjectManagerRoute,
  SettingsRoute: SettingsRoute,
  StructuralToolkitRoute: StructuralToolkitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
